language: python
python:
  - '3.6'
cache:
  pip: true
  directories:
    - /home/travis/.yarn-cache/
before_install:
  - nvm install 10
install: pip install pytest "jupyterlab~=1.0"
script:
  - python setup.py sdist
  - pip install jupyterlab_git[test] --pre --no-index --find-links=dist --no-deps --no-cache-dir -v
  - pip install jupyterlab_git[test]
  - jupyter labextension list
  - jupyter lab build
  - pytest jupyterlab_git -r ap
  - jlpm run test
  - python -m jupyterlab.browser_check
  - jlpm run lint
  - python tests/test-browser/run_browser_test.py
